#define GLC_POINT_SIZE          100

#define GLC_MAX_CURRENT_FONT	16
#define GLC_MAX_FONT		16
#define GLC_MAX_TEXTURE_OBJECT	16
#define GLC_MAX_MASTER		16
#define GLC_MAX_FACE_PER_MASTER	16
#define GLC_MAX_MEASURE		GLC_STRING_CHUNK
#define GLC_MAX_CHARMAP		256
